[project]
name = "uknowuno-project"
version = "0.1.0"
requires-python = ">=3.9"

[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["uknowuno*", "ml*"]
exclude = ["tests*", "scripts*"]